export interface WebApp {
  id: string;
  slug: string;
  name: string;
  description: string;
  url: string;
  category: string;
  tags: string[];
  bannerColor: string;
  icon: string;
  featured: boolean;
}

export const webApps: WebApp[] = [
  {
    id: "1",
    slug: "housecraft-3d",
    name: "HouseCraft 3D",
    description: "Design and visualize your dream home in stunning 3D. Create floor plans, customize interiors, and explore architectural possibilities with intuitive tools.",
    url: "https://housecraft-3d.karthikeyang.me",
    category: "Design & Creative",
    tags: ["3D", "Architecture", "Design", "Visualization"],
    bannerColor: "from-blue-500 to-purple-600",
    icon: "🏠",
    featured: true,
  },
  {
    id: "2",
    slug: "handcricket-game",
    name: "Hand Cricket Game",
    description: "Experience the classic hand cricket game digitally. Challenge AI opponents, track your scores, and relive childhood memories in this nostalgic gaming experience.",
    url: "https://handcricket-game.karthikeyang.me",
    category: "Games & Entertainment",
    tags: ["Game", "Cricket", "Sports", "Multiplayer"],
    bannerColor: "from-green-500 to-teal-600",
    icon: "🏏",
    featured: false,
  },
  {
    id: "3",
    slug: "omni-converter",
    name: "Omni Converter",
    description: "Universal conversion tool supporting units, currencies, file formats, and more. Your all-in-one solution for any conversion need.",
    url: "https://omni-converter.karthikeyang.me",
    category: "Productivity",
    tags: ["Converter", "Utility", "Tools", "Productivity"],
    bannerColor: "from-orange-500 to-red-600",
    icon: "🔄",
    featured: true,
  },
  {
    id: "4",
    slug: "photo-editing-suite",
    name: "Photo Editing Suite",
    description: "Professional-grade photo editing in your browser. Apply filters, adjust colors, add effects, and transform your images with powerful editing tools.",
    url: "https://photo-editing-suite.karthikeyang.me",
    category: "Design & Creative",
    tags: ["Photo", "Editing", "Creative", "Filters"],
    bannerColor: "from-pink-500 to-rose-600",
    icon: "📸",
    featured: true,
  },
  {
    id: "5",
    slug: "audio-editor",
    name: "Audio Editor",
    description: "Edit, mix, and master audio tracks online. Cut, merge, apply effects, and produce professional-quality audio without complex software.",
    url: "https://audio-editor.karthikeyang.me",
    category: "Design & Creative",
    tags: ["Audio", "Music", "Editing", "Sound"],
    bannerColor: "from-purple-500 to-indigo-600",
    icon: "🎵",
    featured: false,
  },
  {
    id: "6",
    slug: "sms-mgmt",
    name: "SMS Management",
    description: "Comprehensive SMS management platform. Organize, schedule, and send bulk messages with advanced analytics and delivery tracking.",
    url: "https://sms-mgmt.karthikeyang.me",
    category: "Communication",
    tags: ["SMS", "Messaging", "Management", "Communication"],
    bannerColor: "from-cyan-500 to-blue-600",
    icon: "💬",
    featured: false,
  },
  {
    id: "7",
    slug: "wordapp",
    name: "WordApp",
    description: "Modern word processor with real-time collaboration. Create, edit, and format documents with rich text editing and cloud sync.",
    url: "https://wordapp.karthikeyang.me",
    category: "Productivity",
    tags: ["Document", "Editor", "Writing", "Collaboration"],
    bannerColor: "from-blue-600 to-indigo-700",
    icon: "📝",
    featured: false,
  },
  {
    id: "8",
    slug: "developer-toolkit",
    name: "Developer Toolkit",
    description: "Essential tools for developers in one place. JSON formatter, Base64 encoder, regex tester, code minifier, and 50+ developer utilities.",
    url: "https://developer-toolkit.karthikeyang.me",
    category: "Development",
    tags: ["Developer", "Tools", "Coding", "Utilities"],
    bannerColor: "from-gray-700 to-gray-900",
    icon: "⚙️",
    featured: true,
  },
  {
    id: "9",
    slug: "ai-quiz",
    name: "AI Quiz Generator",
    description: "AI-powered quiz creation and learning platform. Generate custom quizzes, track progress, and enhance learning with intelligent assessments.",
    url: "https://ai-quiz.karthikeyang.me",
    category: "Education",
    tags: ["AI", "Quiz", "Learning", "Education"],
    bannerColor: "from-violet-500 to-purple-600",
    icon: "🧠",
    featured: true,
  },
  {
    id: "10",
    slug: "design-tool-suite",
    name: "Design Tool Suite",
    description: "Complete design toolkit with vector graphics, mockups, and prototyping. Create stunning designs with professional-grade tools.",
    url: "https://design-tool-suite.karthikeyang.me",
    category: "Design & Creative",
    tags: ["Design", "Graphics", "Vector", "UI/UX"],
    bannerColor: "from-fuchsia-500 to-pink-600",
    icon: "🎨",
    featured: true,
  },
  {
    id: "11",
    slug: "graph-editorpro",
    name: "Graph Editor Pro",
    description: "Advanced graph and diagram editor. Create flowcharts, network diagrams, org charts, and visualize data relationships with ease.",
    url: "https://graph-editorpro.karthikeyang.me",
    category: "Productivity",
    tags: ["Graph", "Diagram", "Flowchart", "Visualization"],
    bannerColor: "from-emerald-500 to-green-600",
    icon: "📊",
    featured: false,
  },
  {
    id: "12",
    slug: "all-in-one-tool",
    name: "All-in-One Tool",
    description: "Swiss army knife of web tools. Combines multiple utilities into one powerful platform for maximum productivity.",
    url: "https://all-in-one-tool.karthikeyang.me",
    category: "Productivity",
    tags: ["Multi-tool", "Utility", "Productivity", "All-in-one"],
    bannerColor: "from-yellow-500 to-orange-600",
    icon: "🛠️",
    featured: true,
  },
  {
    id: "13",
    slug: "omniverse-os",
    name: "Omniverse OS",
    description: "Web-based operating system experience. Access apps, manage files, and work in a complete desktop environment from your browser.",
    url: "https://omniverse-os.karthikeyang.me",
    category: "Platform",
    tags: ["OS", "Desktop", "Virtual", "Platform"],
    bannerColor: "from-slate-600 to-blue-800",
    icon: "💻",
    featured: true,
  },
  {
    id: "14",
    slug: "event-manager",
    name: "Event Manager",
    description: "Plan, organize, and manage events effortlessly. Handle registrations, schedules, tickets, and attendee communication in one platform.",
    url: "https://event-manager.karthikeyang.me",
    category: "Productivity",
    tags: ["Events", "Planning", "Management", "Organization"],
    bannerColor: "from-red-500 to-pink-600",
    icon: "📅",
    featured: false,
  },
  {
    id: "15",
    slug: "code-with",
    name: "Code With",
    description: "Collaborative coding platform. Code together in real-time, share projects, and learn programming with interactive tutorials.",
    url: "https://code-with.karthikeyang.me",
    category: "Development",
    tags: ["Coding", "Collaboration", "Learning", "IDE"],
    bannerColor: "from-indigo-600 to-purple-700",
    icon: "👨‍💻",
    featured: true,
  },
  {
    id: "16",
    slug: "games",
    name: "Games Hub",
    description: "Collection of fun and addictive web games. Play puzzle games, arcade classics, and casual games directly in your browser.",
    url: "https://games.karthikeyang.me",
    category: "Games & Entertainment",
    tags: ["Games", "Entertainment", "Arcade", "Puzzle"],
    bannerColor: "from-lime-500 to-green-600",
    icon: "🎮",
    featured: false,
  },
  {
    id: "17",
    slug: "chat-app",
    name: "Chat Application",
    description: "Real-time messaging platform. Connect with friends, create groups, share media, and communicate instantly with end-to-end encryption.",
    url: "https://chat-app.karthikeyang.me",
    category: "Communication",
    tags: ["Chat", "Messaging", "Real-time", "Social"],
    bannerColor: "from-teal-500 to-cyan-600",
    icon: "💭",
    featured: true,
  },
  {
    id: "18",
    slug: "universal-translator",
    name: "Universal Translator",
    description: "Translate text, documents, and conversations across 100+ languages. Powered by AI for accurate and natural translations.",
    url: "https://universal-transulater.karthikeyang.me",
    category: "Productivity",
    tags: ["Translation", "Language", "AI", "Communication"],
    bannerColor: "from-sky-500 to-blue-600",
    icon: "🌐",
    featured: false,
  },
  {
    id: "19",
    slug: "sms",
    name: "SMS Gateway",
    description: "Send and receive SMS messages programmatically. API-driven platform for integrating SMS into your applications.",
    url: "https://sms.karthikeyang.me",
    category: "Communication",
    tags: ["SMS", "API", "Gateway", "Messaging"],
    bannerColor: "from-blue-500 to-indigo-600",
    icon: "📱",
    featured: false,
  },
  {
    id: "20",
    slug: "voice-calculate",
    name: "Voice Calculator",
    description: "Hands-free calculation using voice commands. Speak your math problems and get instant results with voice-activated computing.",
    url: "https://voice-calculate.karthikeyang.me",
    category: "Productivity",
    tags: ["Voice", "Calculator", "AI", "Accessibility"],
    bannerColor: "from-amber-500 to-orange-600",
    icon: "🎤",
    featured: false,
  },
  {
    id: "21",
    slug: "calculator-tool",
    name: "Advanced Calculator",
    description: "Scientific calculator with advanced functions. Solve complex equations, plot graphs, and perform statistical analysis.",
    url: "https://calculator-tool.karthikeyang.me",
    category: "Productivity",
    tags: ["Calculator", "Math", "Science", "Tools"],
    bannerColor: "from-stone-600 to-gray-700",
    icon: "🔢",
    featured: false,
  },
  {
    id: "22",
    slug: "pulsestep-blindshoe",
    name: "PulseStep BlindShoe",
    description: "Assistive technology for visually impaired navigation. Smart shoe system with haptic feedback and obstacle detection.",
    url: "https://pulsestep-blindshoe.karthikeyang.me",
    category: "Innovation",
    tags: ["Accessibility", "IoT", "Innovation", "Assistive Tech"],
    bannerColor: "from-violet-600 to-purple-700",
    icon: "👟",
    featured: true,
  },
  {
    id: "23",
    slug: "cs-lab",
    name: "CS Lab",
    description: "Computer science learning laboratory. Practice algorithms, data structures, and programming concepts with interactive exercises.",
    url: "https://cs-lab.karthikeyang.me",
    category: "Education",
    tags: ["Computer Science", "Learning", "Algorithms", "Education"],
    bannerColor: "from-cyan-600 to-blue-700",
    icon: "🔬",
    featured: false,
  },
];

export const categories = [
  "All",
  "Design & Creative",
  "Games & Entertainment",
  "Productivity",
  "Communication",
  "Development",
  "Education",
  "Platform",
  "Innovation",
];
